server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/file
    username: root
    password: 123456789
    hikari:
      auto-commit: false
  main:
    allow-circular-references: true

  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true
        hbm2ddl:
          auto: update


#  mybatis:
#    type-aliases-package: com.ohgiraffers.forepeproject.postAttachment.command.domain.aggregate.entity
#    mapper-locations: mybatis/mapper/*.xml
#    config : mybatis-config.xml



jwt:
  secret: asdfjp298pafo1320efqw0udvnh0er0h412r08byfdq9dsvh02143908hfeqwn80fdqs0nfdqs0n412013rq0nqefn08dfas0das730732g86923kjefho43y592y095r2wofhw92yt832y5r920woqhjfwoty28rt02ty230hwot92ty0923752rywohr9wyf823y8329yt0wyf9stgf932y20gfy9w8yh28it2y3y239836y25720hw8fy83r49y23y8

logging:
  level:
    org:
      springframework:
        security: DEBUG

